# Generated by Django 3.0 on 2020-03-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expnspage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemno', models.IntegerField()),
                ('itemname', models.CharField(max_length=64)),
                ('purchasedate', models.DateField()),
                ('remarks', models.CharField(max_length=64)),
            ],
        ),
    ]
