# Generated by Django 3.0 on 2020-04-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemno', models.IntegerField()),
                ('itemname', models.CharField(max_length=64)),
                ('amount', models.IntegerField()),
                ('purchasedate', models.DateField()),
                ('remarks', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Expnspage',
        ),
    ]
