# Generated by Django 3.0 on 2020-04-07 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_remove_user_creationdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
